# Generated by Django 3.2.19 on 2023-05-31 09:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Toker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.GenericIPAddressField()),
                ('port', models.IntegerField(validators=[django.core.validators.MinValueValidator, django.core.validators.MaxValueValidator])),
                ('recive', models.TextField()),
                ('res', models.CharField(max_length=1024)),
                ('target_path', models.CharField(max_length=512)),
                ('ini_path', models.CharField(max_length=512)),
            ],
        ),
    ]
